### ISSUE TITLE
Migrate documentation to Documenter

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/HypothesisTests.jl#103]
The following things would need to happen as part of the migration:

* Rename doc/ to docs/ (`git mv doc docs`)
* Convert ReST files to Markdown
* Move specific method and type documentation to docstrings

**Comment by BenjaminBorn** [comment]
Would you prefer all of this in one big pull request or would it be ok to go step by step? If it's ok, I would start with a PR that moves specific method and type documentation to docstrings.

**Comment by ararslan** [comment]
Sure, that'd be fantastic!

**Comment by BenjaminBorn** [comment]
I also managed to build the new docs locally using Documenter with native HTML output. I'll send a PR once #106 is merged. If I understand it correctly (I'm a total Documenter noob), we need Travis and Github keys. @ararslan can you set them up for the repository?

**Comment by ararslan** [comment]
Can do.

**Comment by ararslan** [comment]
Keys added and gh-pages branch created.

**Comment by ararslan** [comment]
This task has been valiantly completed by the intrepid @BenjaminBorn.
