### ISSUE TITLE
ChisqTest return DomainError sqrt will only return a complex result if called with a complex argument. Try sqrt(complex(x)).

### ISSUE THREAD

**Issue by kskoeld** [JuliaStats/HypothesisTests.jl#125]
Am trying to use the function with some larger dataset.
In a number of cases I'm getting the error below.
E.g.
`ChisqTest([153374 578;222198 788])
`

Error I'm getting

> DomainError:
> sqrt will only return a complex result if called with a complex argument. Try sqrt(complex(x)).
> 
>  in sqrt at operators.jl:381
>  in PowerDivergenceTest at /home/ubuntu/.julia/v0.4/HypothesisTests/src/power_divergence.jl:253
>  in ChisqTest at /home/ubuntu/.julia/v0.4/HypothesisTests/src/power_divergence.jl:274

Using v 0.2.10 in a Julia 0.4.7 Jupyter notebook

**Comment by andreasnoack** [comment]
This issue was fixed a while ago so please update your packages (and your Julia installation)

**Comment by andreasnoack** [comment]
I can reproduce the error but I think this one is a bit different that the other one. It's been a while but I think the original issue here was integer overflow. In this case, the error is thrown from this computation. I'm not sure what the computation is supposed to do, though.
https://github.com/JuliaStats/HypothesisTests.jl/blob/a89145162648df8b37303894211c0ce7f197f065/src/power_divergence.jl#L133-L182
