### ISSUE TITLE
p val > 1 in ExactMannWhitneyUTest 

### ISSUE THREAD

**Issue by nw11** [JuliaStats/HypothesisTests.jl#126]
```
A = [ 1.34937, 1.75722,0.276514, 1.04546 , 1.69085 , 0.738085, 2.36313 ]
B = [ 2.62325 , 1.16533 , 1.1327  ,  0.728714]

julia>ExactMannWhitneyUTest(A,B)
Exact Mann-Whitney U test
-------------------------
Population details:
    parameter of interest:   Location parameter (pseudomedian)
    value under h_0:         0
    point estimate:          0.20035500000000006

Test summary:
    outcome with 95% confidence: fail to reject h_0
    two-sided p-value:           1.0727272727272728

Details:
    number of observations in each group: [7, 4]
    Mann-Whitney-U statistic:             14.0
    rank sums:                            [41.0, 25.0]
    adjustment for ties:                  0.0
```

**Comment by ararslan** [comment]
Wow, that's extraordinarily probable.

**Comment by andreasnoack** [comment]
I'm not sure this is really a bug. It is a standard issue with two-sided p-values. I've previously made [this comment](https://github.com/JuliaStats/HypothesisTests.jl/issues/98#issuecomment-301532196) although the issue here isn't that the distribution is asymmetric but that the test statistic happens to be the middle outcome of the discrete distribution. Hence, the middle observation is counted twice. I don't think it is big deal. Asymptotically, it won't be larger than one.

**Comment by ararslan** [comment]
It's pretty jarring as a user. Perhaps we could just add a `clamp(pval, 0, 1)` when showing the value?

**Comment by nalimilan** [comment]
I guess we should do whatever other software do.

**Comment by ararslan** [comment]
I don't recall ever having seen a value outside of [0, 1] for p-values in R or SAS.

**Comment by bjarthur** [comment]
glad i'm not the only one who came across this!

**Comment by rpgowers** [comment]
I also found this for a case where U1 = U2, e.g.
```
a = [12,10,7,6,3,1]
b = [11,9,8,5,4,2]
```
Where 

`MannWhitneyUTest(a,b)`

yields an error:
```
Exact Mann-Whitney U test
-------------------------
Population details:
    parameter of interest:   Location parameter (pseudomedian)
    value under h_0:         0
    point estimate:          0.0

Error showing value of type ExactMannWhitneyUTest{Float64}:
ERROR: p-values must be in [0; 1]
```
whilst
`pvalue(MannWhitneyUTest(a,b))`
simply gives 1.0627705627705626 without any kind of warning.

**Comment by pdeffebach** [comment]
R clamps at `1`

```
r$> a = c(12, 10, 7, 6, 3, 1)                                              

r$> b = c(11, 9, 8, 5, 4, 2)                                               

r$> m = wilcox.test(a, b)                                                  

r$> m$p.value                                                              
[1] 1
```
