### ISSUE TITLE
updates for julia 0.7

### ISSUE THREAD

**Issue by nico202** [JuliaStats/HypothesisTests.jl#127]
Any plan on updating? 

Thanks

**Comment by ararslan** [comment]
Yeah definitely, just hasn't happened yet. It will require some dependent packages to support 0.7 first, e.g. Distributions.

**Comment by nico202** [comment]
Yeah the number of packages supporting 0.7 is still extremely low .-. Maybe I'll have a look at the changes required to fix the dependencies

**Comment by ararslan** [comment]
Fixed by #130.
