### ISSUE TITLE
Bump Combinatorics version

### ISSUE THREAD

**Issue by jtackm** [JuliaStats/HypothesisTests.jl#173]
I'm getting unsatisfiable requirements issues when trying to install HypothesisTests.jl alongside packages that require Combinatorics v1.0.0:

```
(v1.3) pkg> add HypothesisTests
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HypothesisTests [09f84164]:
 HypothesisTests [09f84164] log:
 ├─possible versions are: [0.7.0, 0.8.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.7.0, 0.8.0]
 └─restricted by compatibility requirements with Combinatorics [861a8166] to versions: uninstalled — no versions left
   └─Combinatorics [861a8166] log:
     ├─possible versions are: [0.7.0, 1.0.0] or uninstalled
     └─restricted to versions 1.0.0 by an explicit requirement, leaving only versions 1.0.0
```

The reason being that HypothesisTest's REQUIRE restricts the Combinatorics version to v0.7 (which used to be a lower bound, but is now interpreted as an exact bound by the package manager, I think). Would it be possible to increase the version bound for this dependency?

**Comment by nalimilan** [comment]
AFAICT we allow any version of Combinatorics above 0.7: https://github.com/JuliaRegistries/General/blob/master/H/HypothesisTests/Compat.toml

Can you try running `]free Combinatorics` and `]free HypothesisTests`?

**Comment by jtackm** [comment]
After running the free commands the problem unfortunately still persists. Even in a new environment, after installing HypothesisTests, I can't install Combinatorics v1.0.0:

```
(hypothesistests_bug) pkg> add Combinatorics@1.0.0
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HypothesisTests [09f84164]:
 HypothesisTests [09f84164] log:
 ├─possible versions are: [0.7.0, 0.8.0] or uninstalled
 ├─restricted to versions 0.8.0 by an explicit requirement, leaving only versions 0.8.0
 └─restricted by compatibility requirements with Combinatorics [861a8166] to versions: uninstalled — no versions left
   └─Combinatorics [861a8166] log:
     ├─possible versions are: [0.7.0, 1.0.0] or uninstalled
     └─restricted to versions 1.0.0 by an explicit requirement, leaving only versions 1.0.0
```

**Comment by nalimilan** [comment]
Too bad. I've merged https://github.com/JuliaStats/HypothesisTests.jl/pull/169, hopefully if we tag a new release it should fix this.

**Comment by jtackm** [comment]
Thanks for the effort, I can confirm that the issue is resolved now using `HypothesisTests#master`

**Comment by racinmat** [comment]
When can we expect new tag release?

**Comment by nalimilan** [comment]
We're waiting on https://github.com/JuliaStats/HypothesisTests.jl/pull/176 as we have to tag a new breaking release, so we want to fix API issues we have identified at the same time.

**Comment by nalimilan** [comment]
See https://github.com/JuliaRegistries/General/pull/8107
