### ISSUE TITLE
Test for heteroskedasticity (White's etc)

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaStats/HypothesisTests.jl#199]
I believe we need a test for heteroskedasticity (in a regression model). Or is it already available?

The idea of White's test is to use regress residual^2 on the regressors, their squares and (optionally) also their cross products - and test whether all slopes are zero or not. This can be implemented in terms of the R2 of this auxilliary regression. The Breusch-Pagan version is to use just the linear terms. 

EDIT: suggested function
```
"""
WhitesTest(X,e,TestType="")

Compute the Breusch-Pagan or White's test of heteroskedasticity of the residuals
of a regression model. It is assumed that `X` includes a constant.

# Input
- `X::Array`:          TxK, regressors
- `e::Vector`:         T-vector, residuals
- `TestType::String`:  "Linear" (Breusch-Pagan test), "LinearAndSquares" (White's without cross-products), "" (White's with cross-products)

# Output
- `LM::Float64`:    test statistic, distributed as Chisq(df)
- `LMp::Float64`:   p value of test
- `df::Int`:        degrees of freedom in test

"""
function WhitesTest(X,e,TestType="")

  (T,K) = (size(X,1),size(X,2))    #nobs,nvars

  if TestType == "Linear"
    z  = X
  elseif TestType == "LinearAndSquares"
    z = [X X.^2]
  else               #linear, squares and cross-products
    z = fill(NaN,T,round(Int,K*(K+1)/2))   #loop is easier and quicker than index tricks
    vv = 1
    for i = 1:K, j = i:K
      z[:,vv] = X[:,i].*X[:,j]             #eg. x1*x1, x1*x2, x2*x2
      vv      = vv + 1
    end
  end

  df  = rank(z) - 1                         #number of independent regressors in z
  e2  = e.^2
  b   = z\e2
  res = e2 - z*b
  R2  = 1 - var(res)/var(e2)
  LM  = T*R2                                #T*R2 in original papers, could also use T*R2/(1-R2)
  LMp = 1 - cdf(Chisq(df),LM)

  return LM, LMp, df

end
```

I might need help with applying the common HypothesisTests.jl interface.

Should I go ahead?

**Comment by PaulSoderlind** [comment]
I've now tested and also benchmarked against R. The interface should be doable, but I have one _question_: the test comes in three flavours (see `TestType` above). What is the preferred way of interfacing that? Does the package have a standard for such cases?

**Comment by wildart** [comment]
First, you would need to add a structure type with a test statistics & any auxiliary values, e.g.

```julia
struct VarianceFTest <: HypothesisTest
    LM::Float64  # test statistic, distributed as Chisq(df)
    df::Int  #degrees of freedom in test
end
```

Next, you need to override several methods
```julia
StatsBase.dof(t::VarianceFTest) = t.df
pvalue(t::VarianceFTest; tail=:right) = pvalue(Chisq(dof(t)), t.LM, tail=tail)
testname(t::VarianceFTest) = "the name of the test"
```
There are two more additional methods: `population_param_of_interest` & `default_tail`. See if you can provide some overrides,
https://github.com/JuliaStats/HypothesisTests.jl/blob/125bfd1b894cbae69d2345ca6a7892f473a05f17/src/HypothesisTests.jl#L146-L150

And finally, you override `show` function to give a formatted output
```julia
function show_params(io::IO, t::VarianceFTest, indent="")
    println(io, indent, "χ² statistic:           ", t.LM)
    println(io, indent, "degrees of freedom:     ", dof(t))
end
```

**Comment by PaulSoderlind** [comment]
closed by PR https://github.com/JuliaStats/HypothesisTests.jl/pull/206
