### ISSUE TITLE
two sample kstest had different pvalue compared to scipy

### ISSUE THREAD

**Issue by testercwt** [JuliaStats/HypothesisTests.jl#209]
0.0135 vs. 0.007936507936507936 in two sample ks
----------------------------------------------
ApproximateTwoSampleKSTest(1:5,6:10)

Approximate two sample Kolmogorov-Smirnov test

Population details:
    parameter of interest:   Supremum of CDF differences
    value under h_0:         0.0
    point estimate:          1.0

Test summary:
    outcome with 95% confidence: reject h_0
    two-sided p-value:           0.0135

Details:
    number of observations:   [5,5]
    KS-statistic:              1.5811388300841898

------
using PyCall
st=pyimport("scipy.stats")
st.ks_2samp(1:5,6:10)
(1.0, 0.007936507936507936)

**Comment by nalimilan** [comment]
Can you try with `mode='asymp'` in Python? Their docs say they use the exact distribution when there are fewer than 1000 entries, which isn't the case of ours.

**Comment by testercwt** [comment]
you are right

**Comment by testercwt** [comment]
> Can you try with `mode='asymp'` in Python? Their docs say they use the exact distribution when there are fewer than 1000 entries, which isn't the case of ours.

you are right
