### ISSUE TITLE
Enhancement suggestion: Significance of Pearson Correlation Coefficient

### ISSUE THREAD

**Issue by Jo-Fleck** [JuliaStats/HypothesisTests.jl#219]
The command `Statistics.cor` currently has no option to compute significance levels (p-values). 

I asked about this on [discourse](https://discourse.julialang.org/t/compute-significance-of-pearson-correlation-coefficient/49589) and was pointed to the [Partial Correlation Test](https://juliastats.org/HypothesisTests.jl/stable/multivariate/#Partial-correlation-test-1) of HypothesisTest.jl which includes this feature.

It could be helpful to add it to the standard (non-partial) correlation test.

(I'll also add this suggestion to the Statistics package as well.)

**Comment by nalimilan** [comment]
Fixed by https://github.com/JuliaStats/HypothesisTests.jl/pull/214/.
