### ISSUE TITLE
Help with the reviewing process

### ISSUE THREAD

**Issue by viraltux** [JuliaStats/HypothesisTests.jl#240]
Hi guys, I see there are some pull requests taking a very long time to review despite they are fixing some simple problems. I imagine you're really busy and that's why I wonder if you would like some help with the reviewing process.

**Comment by viraltux** [comment]
I guess not

**Comment by nalimilan** [comment]
Yes of course help reviewing PRs is always welcome. Feel free to leave comments on them and/or approve them when you feel they are ready, that may help merging them.
