### ISSUE TITLE
confint take either alpha everywhere or level everywhere

### ISSUE THREAD

**Issue by schlichtanders** [JuliaStats/HypothesisTests.jl#268]
I just came across HypothesisTest.jl and was very surprised to see that the central function `confint` has not a unified interface.

Some use `level` others use `alpha` (=1-level) as the coverage parameter. I am very unsure why such inconsistency is the case in a well known package like HypothesisTest.jl, probably I am missing something.

I would suggest to unify this interface, to support alpha and level everywhere and compute the respective other value as needed.

**Comment by nalimilan** [comment]
Good catch. `alpha` has been deprecated a long time ago, but for some reason it's still used by binomial and power divergence tests. Would you make a pull request to fix this?
