### ISSUE TITLE
Problem with types in ExactPermutationTest

### ISSUE THREAD

**Issue by SilvaSimaoPaulo** [JuliaStats/HypothesisTests.jl#274]
When I try to use the ExactPermutationTest, for example:
` t = ExactPermutationTest([0.3, 0.31, 0.31, 0.32], [0.31, 0.29, 0.29, 0.30], x->10x)`
I got the following error
`ERROR: MethodError: no method matching HypothesisTests.PermutationTest(::Vector{Float64}, ::Vector{Vector{Float64}})
Stacktrace:
 [1] ExactPermutationTest(x::Vector{Float64}, y::Vector{Float64}, f::var"#7#9")
   @ HypothesisTests ~/.julia/packages/HypothesisTests/Dvf6v/src/permutation.jl:26
 [2] top-level scope
   @ REPL[10]:1`
It looks like it is passing the wrong argument types to the internal PermutationTest constructor.

**Comment by wildart** [comment]
The function must return a value for a given vector inputs, e.g. `mean`, but `x->10x` returns a scaled vector, hence the error.
