### ISSUE TITLE
Wald interval with continuity correction

### ISSUE THREAD

**Issue by PharmCat** [JuliaStats/HypothesisTests.jl#292]
PR #291 made for this feature (for consistent with other statistical software).

But it can be made with 0.5/n correction:

[Pires, Ana & Amado, Conceição. (2008). Interval Estimators for a Binomial Proportion: Comparison of Twenty Methods. REVSTAT. 6. 10.57805/revstat.v6i2.63. ](https://www.researchgate.net/publication/237465854_Interval_estimators_for_a_binomial_proportion_Comparison_of_twenty_methods)

[https://search.r-project.org/CRAN/refmans/DescTools/html/BinomCI.html](https://search.r-project.org/CRAN/refmans/DescTools/html/BinomCI.html)

And with 1/n correction:

[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4958484/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4958484/)

Now it made with 0.5/n correction.

**Comment by ararslan** [comment]
Closed by #291 :)
