### ISSUE TITLE
Add documentation link on the about section.

### ISSUE THREAD

**Issue by biplab37** [JuliaStats/HypothesisTests.jl#298]
It would be nice if one can add the link to the [documentation](http://juliastats.org/HypothesisTests.jl/stable/) in the about section of this github repo. It will make it easier for people to find the docs directly from the repository. Right now one can find the link by clicking on the github pages then clicking `View Deployment`.

**Comment by ararslan** [comment]
There are links to the stable and development versions of the documentation in the repository's README. Do you find that isn't sufficiently discoverable?

**Comment by biplab37** [comment]
Oops. Sorry. My bad.
