### ISSUE TITLE
[Feature Proposal] add new StatsAPI function to extract statistics

### ISSUE THREAD

**Issue by babaq** [JuliaStats/HypothesisTests.jl#306]
Currently, only `pvalue` and `confint` were proposed and supported by different tests, but sometimes the underlying test statistics were of interest. It would be a more consistent and convenient way to extract statistics by adding new API like `stats`.

**Comment by ararslan** [comment]
Duplicate of https://github.com/JuliaStats/HypothesisTests.jl/issues/79 🙂

**Comment by ararslan** [comment]
I've finally proposed a solution to that issue, 7 years after opening it: https://github.com/JuliaStats/StatsAPI.jl/pull/24. Feel free to comment there or the original issue if you have further input to provide. Thanks!
