### ISSUE TITLE
doc strings missing for `HypothesisTest`s

### ISSUE THREAD

**Issue by diegozea** [JuliaStats/HypothesisTests.jl#59]
Would be great to have documentation on the REPL for `HypothesisTest` types. The documentation on the page is fine, it could be moved into doc strings. 
Also, It would be great to add an _assumptions_ section for each test. 

Best,

**Comment by BenjaminBorn** [comment]
The reverse problem also exists. I have added a couple of tests that have docstrings but do not appear in the online documentation.

Would it make sense to move the complete documentation to Documenter.jl? What would be the first step? Transfer the information in the `.rst` files into docstrings?

**Comment by ararslan** [comment]
@BenjaminBorn Yes, we definitely want to set up Documenter here. I've opened an issue for it: https://github.com/JuliaStats/HypothesisTests.jl/issues/103.
