### ISSUE TITLE
Dependency broken on v0.5

### ISSUE THREAD

**Issue by ranjanan** [JuliaStats/HypothesisTests.jl#63]
The dependency `CurveFit` in the `REQUIRE` file is broken on v0.5. (https://github.com/pjabardo/CurveFit.jl/issues/6)

There is a PR to fix this. (https://github.com/pjabardo/CurveFit.jl/pull/7) Is there anyone here who can review and merge please?

**Comment by ararslan** [comment]
#62 here removes the CurveFit dependency entirely, but there's still work to be done on that PR.

Since CurveFit is on a user's account rather than an organization's, it would require a collaborator to merge. Looks like the only contributor to that repo so far has been the original author, so I'd be surprised if anyone here had the permissions necessary to merge there.

**Comment by ararslan** [comment]
Actually, it appears that CurveFit may have been effectively superseded by JuliaOpt/LsqFit.jl.

**Comment by ranjanan** [comment]
@ararslan I was aware of that, but currently for users of this package on v0.5, this package would break because of the dependency. This was to address specifically that. 

>Actually, it appears that CurveFit may have been effectively superseded by JuliaOpt/LsqFit.jl.

Do you think it makes sense to remove CurveFit from the REQUIRE and add LsqFit instead?

**Comment by ararslan** [comment]
Maybe, but that wouldn't fix all of the issues this package currently has on 0.5. If you look at the [0.5 test log](http://pkg.julialang.org/logs/HypothesisTests_0.5.log) from the package evaluator, it's having the p-value issue with the block test that I mentioned in #62. I'm not familiar with that particular test so I'm not entirely sure how to proceed with fixing that. 😕

**Comment by ranjanan** [comment]
Actually the function `ccdf` from `Distributions.jl` is behaving differently. That's why you're seeing this error. On v0.4, it gives 0.24 and on v0.5 it gives 0.96. Digging into it....

**Comment by ararslan** [comment]
Great catch, @ranjanan! Thanks for looking into it!

**Comment by ranjanan** [comment]
Oh wait, sorry. What actually is that the inputs to that function are changing when you call the `BTest` constructor.

**Comment by ranjanan** [comment]
Hey, I managed to trace the issue. This is due difference in behaviour of `randperm` from v0.4 to v0.5 even with the same seed. Consider the following code. 

```julia
function thing(uniform = false)
    srand(1)

    X = [8.5415 37.0043; 14.7532 29.2931; 75.5506 28.3312; 29.4645 15.6710; 55.3216 12.3864; 71.9396 43.6335; 32.9615 31.0025; 15.8288 60.9634; 62.5720 61.7679; 59.7134 43.0258; 60.6645 29.5431; 14.0132 45.7089; 58.9875 57.6634; 20.7221 66.7510; 13.4842 56.4697; 59.7120 31.7011; 40.9415 56.8771; 71.6981 71.4109; 30.6346 61.2081; 28.0781 29.2852; 31.0662 30.1430; 57.7878 43.0160; 13.3660 28.4529; 14.4294 43.1398; 60.5189 31.8989; 46.4873 61.3727; 63.1827 16.7833; 29.5423 60.1772; 22.6857 23.5714; 46.9106 44.9033; 32.2429 60.4309; 14.8121 16.1449; 46.5136 14.8556; 12.4426 12.0594; 14.2558 28.6762; 31.3229 76.4065; 8.7645 27.4488; 58.6321 42.0109; 56.5313 70.8958; 32.1743 16.5879]

    ssize = 20

    a = X[1:ssize,:]
    b = X[(ssize+1):end,:]

    kernel = HypothesisTests.rbf

    n = size(a,1)
    @show randperm(n)
    if uniform
        idx = [14,9,8,17,15,11,7,20,18,1,4,5,16,2,12,19,6,13,10,3]
    else
        idx = randperm(n)
    end
    X, Y = a[idx,:], b[idx,:]

    blocksize = 4

    n2::Int = floor(n / blocksize)
    hh = zeros(n2)
    tmp = zeros(n2)
    for i = 1:blocksize
        offset1 = n2*(i-1)
        for j = (i+1):blocksize
            offset2 = n2*(j-1)
            broadcast!(+, hh, hh, kernel(tmp, X, offset1, X, offset2))
            broadcast!(+, hh, hh, kernel(tmp, Y, offset1, Y, offset2))
            broadcast!(-, hh, hh, kernel(tmp, X, offset1, Y, offset2))
            broadcast!(-, hh, hh, kernel(tmp, Y, offset1, X, offset2))
        end
    end
    MMD = mean(hh)
    stderr = std(hh)/sqrt(n2)
    (MMD, stderr)
end
```

On Julia v0.4:
```
julia> thing()
randperm(n) = [14,9,8,17,15,11,7,20,18,1,4,5,16,2,12,19,6,13,10,3]
(-0.017047035122149216,0.21585657092456648)

julia> thing(true)
randperm(n) = [14,9,8,17,15,11,7,20,18,1,4,5,16,2,12,19,6,13,10,3]
(0.07731715365611422,0.14946126794670944)
```

On Julia v0.5:

**Comment by ranjanan** [comment]
On v0.4, 
```
julia> srand(1); randperm(10)
10-element Array{Int64,1}:
  2
  9
  8
  6
  5
  4
  7
  3
 10
  1
```
On v0.5: 
```
julia> srand(1); randperm(10)
10-element Array{Int64,1}:
 10
  3
  7
  8
  9
  2
  5
  6
  4
  1
```

**Comment by ararslan** [comment]
Excellent sleuthing, @ranjanan, thanks so much for your help. Looks like it was https://github.com/JuliaLang/julia/commit/fd93d4555900ecf39a75d4c02c385cacf8c942fb that introduced the difference in behavior. If I define a new `randperm` that matches the definition prior to the change, I get the same result as 0.4:

```julia
julia> function randperm2(n::Integer)
           a = Array{typeof(n)}(n)
           n == 0 && return a
           a[1] = 1
           @inbounds for i = 2:n
               j = rand(Base.Random.GLOBAL_RNG, 1:i)
               a[i] = a[j]
               a[j] = i
           end
           return a
       end
randperm2 (generic function with 1 method)

julia> srand(1); randperm2(10)
10-element Array{Int64,1}:
  2
  9
  8
  6
  5
  4
  7
  3
 10
  1
```

**Comment by simonbyrne** [comment]
As I said on the issue in Base, in general, we've not preserved the behaviour of random functions and seeds between versions. I think if the p-value is fluctuating that much, then there is either something wrong with the source code (unfortunately I don't really know anything about B tests) or the tests (would using a larger sample help?).

**Comment by ararslan** [comment]
I don't know anything about B tests either, but I did find a MATLAB implementation that accompanies the paper referenced here. Couldn't modify it sufficiently to get it to work in Octave and compare with this, unfortunately. The MATLAB code is GPL licensed and the B test code here bears striking similarity (particularly in its original incarnation, before optimizations), which is a little concerning...

Regardless, I feel like randomness shouldn't affect the p-value that drastically for a given set of data. (But again, dunno about B tests)

**Comment by simonbyrne** [comment]
Hmm, it does look like it was based on the GPL code, we should tread carefully.

@BigCrunsh Can you help us out here?

**Comment by simonbyrne** [comment]
Given that (a) the tests are failing, (b) no one seems to know why, and (c) the licence is somewhat suspect, should we remove the code, or at least move it into a quarantine subdirectory?

**Comment by ararslan** [comment]
I would vote to remove it for now. We can always revert the commit that does it at a later time once we figure things out.

**Comment by ararslan** [comment]
I put together a PR (#65) that removes the test. What do you guys think?

**Comment by ararslan** [comment]
cc @nalimilan @andreasnoack

**Comment by ararslan** [comment]
The B test is gone for now, things work on 0.4 and 0.5, and a new version has been tagged.
