### ISSUE TITLE
ChisqTest failed

### ISSUE THREAD

**Issue by jianixrabbit** [JuliaStats/HypothesisTests.jl#64]
`x = [288047,80112,516752,8628,166,8440,11730,3933] `
`y =  [328936,81834,513065,8570,260,10611,12649,4196]`
`ChisqTest(hcat(x,y))`

result output is

`LoadError: DomainError:
sqrt will only return a complex result if called with a complex argument. Try sqrt(complex(x)).
while loading In[6], in expression starting on line 1`

**Comment by ararslan** [comment]
The chi-squared test is using the power divergence test under the hood, which was noted to have issues with [integer overflow](https://en.wikipedia.org/wiki/Integer_overflow). This is causing the issues with `sqrt`. I'm going to close this as a duplicate of #43, which is being addressed by #44.
