### ISSUE TITLE
Use StatsBase.confint instead of ci

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/HypothesisTests.jl#67]
Currently HypothesisTests defines a function `ci` for computing confidence intervals. However, it seems to me that we should be using `confint` from StatsBase and extending it for each test. Is there a reason why we should continue to prefer `ci` or would it make sense to switch over to `confint`?

**Comment by andreasnoack** [comment]
They should definitely use the same name. I'll vote for `confint`.

**Comment by ararslan** [comment]
Agreed. It's certainly a more descriptive name than `ci`, and folks using this package that are familiar with other packages that *do* extend `confint` would likely be confused if we don't conform.
