### ISSUE TITLE
U not defined in MannWhitneyUTest

### ISSUE THREAD

**Issue by rand5** [JuliaStats/HypothesisTests.jl#68]
I have been using the MannWhitneyUTest for a while and just ran into an error today that I had not seen before. Here is a MWE:

`o1 = [0.513503`
 `0.289973`
 `0.119931`
 `0.362231]`

`o2 = [0.36834 `
 `0.119931`
 `0.473031`
 `0.256792`
 `0.236628]`

`MannWhitneyUTest(o1,o2)`

> UndefVarError: U not defined in mwuenumerate at C:\Users\X\.julia\v0.4\HypothesisTests\src\mann_whitney.jl:83

Updated the package after I first noticed this, but no change. Doesn't appear to be an issue with the size of the input arrays since 
`MannWhitneyUTest(rand(4),rand(5))`
executes fine.

**Comment by KristofferC** [comment]
Fixed in https://github.com/JuliaStats/HypothesisTests.jl/pull/42? Should probably tag new version...

**Comment by ararslan** [comment]
What version of HypothesisTests are you using? This is what happens when I run your code:
```
julia> MannWhitneyUTest(o1,o2)
ERROR: MethodError: `MannWhitneyUTest` has no method matching MannWhitneyUTest(::Array{Float64,2}, ::Array{Float64,2})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
```
Should work fine if you construct your arrays using commas instead of spaces.

**Comment by rand5** [comment]
@ararslan , Thanks for the comment-- apparently when I quoted the code in the error report, it reformatted it. I have adjusted the original post to accurately reflect what I had typed-- elements defined with carriage returns as opposed to spaces. This results in each of `o1` and `o2` being of type `Array{Float64,1}`.

An interesting point no note is that when I reverse the order of the inputs, i.e. call `MannWhitneyUTest(o2,o1)`, the line executes successfully. 

I have HypothesisTests version 0.2.10 in Julia 0.4.2

**Comment by KristofferC** [comment]
Why am I being ignored :(. As I said this has been fixed in a PR that went in later than the last tagged version. Running `Pkg.checkout("HypothesisTests")` will make it work or if we tag a new version of this package.

**Comment by ararslan** [comment]
@KristofferC Sorry! Didn't mean to ignore you. You and I posted our comments at about the same time I think, I didn't see yours.

I had been waiting to tag a new version until #62 is merged but feel free to tag sooner.

**Comment by ararslan** [comment]
I'll tag a new version momentarily

**Comment by ararslan** [comment]
Looks like this has been fixed.
