### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by tlnagy** [JuliaStats/HypothesisTests.jl#77]
Currently, `HypothesisTests` throws a method overwrite error for `pvalue`. I believe this was recently fixed by @simonster on master, but it is still present in the latest tagged version.

**Comment by tlnagy** [comment]
Pinging @ararslan @garborg @simonster.

**Comment by ararslan** [comment]
Thanks for the reminder, @tlnagy! Will do.

**Comment by tlnagy** [comment]
No worries. thanks.

**Comment by ararslan** [comment]
v0.4.0 has been tagged.
