### ISSUE TITLE
Remove Rmath dependency?

### ISSUE THREAD

**Issue by tlnagy** [JuliaStats/HypothesisTests.jl#80]
Is it feasible to remove the Rmath dependency? It's kind of a pain to install and it's the primary non-julia dependency of my analysis software `tlnagy/Crispulator.jl`.

**Comment by simonster** [comment]
Only if we decide we don't care about an exact Mann-Whitney U test (#7)

**Comment by tlnagy** [comment]
It looks like only two functions, `pwilcox` and `psignrank`, are imported from `Rmath`. Is there anything stopping these from being reimplemented in Julia?

**Comment by tlnagy** [comment]
Ah. I missed that issue. I'm going to go ahead and close this in favor of #7. I might try and see if I can implement something performant in a reasonable amount of time.

**Comment by tlnagy** [comment]
It seems like `StatsFuns` is the bigger fish anyway since it seems to rely on more of the `RMath` library.

**Comment by andreasnoack** [comment]
It's not likely that we'll get rid of `Rmath` anytime soon. The special functions in there are necessary for `Distributions` and would require a lot of labor to reimplement.
