### ISSUE TITLE
Add methods for adjusting p values

### ISSUE THREAD

**Issue by cjprybol** [JuliaStats/HypothesisTests.jl#83]
This is currently available in Julia via https://github.com/dirkschumacher/PValueAdjust.jl

Given that the functionality for calculating p values lives here in HypothesisTests, I thought it would be a good idea to try and implement Bonferroni, FDR, and FWER methods here as well. I saw open pull requests related to p values here https://github.com/JuliaStats/HypothesisTests.jl/pull/73 and here https://github.com/JuliaStats/HypothesisTests.jl/pull/76, but nothing for these simpler tests.

Mainly posting this here as a reminder to try and implement these myself, but any feedback on whether these already exist in JuliaStats and I missed them, that these tests should go elsewhere, or thumbs up/down voting that moving this functionality out of a the PValueAdjust package and into here is a good/bad idea is welcome

**Comment by ararslan** [comment]
I've been meaning for a while to add p-value adjustments here, I just haven't gotten around to it.

**Comment by cjprybol** [comment]
https://github.com/juliangehring/MultipleTesting.jl

**Comment by ararslan** [comment]
Good find, thanks Cameron.
