### ISSUE TITLE
getting p-values into array

### ISSUE THREAD

**Issue by evolgenomology** [JuliaStats/HypothesisTests.jl#85]
Hi, 

I would like to use the KS test on 2000 datasets and each time I run it just retrieve the p-value into an array. Being new to Julia, I wonder how (and if) this is possible. Currently, I am doing
```ApproximateTwoSampleKSTest(x11,y11)```  
which prints out all results to the screen.

Thanks

Philipp

**Comment by ararslan** [comment]
Hello, Philipp. We use the GitHub issue tracker for bug reports and feature requests. For general questions, please post to https://discourse.julialang.org under the statistics category. Thanks!
