### ISSUE TITLE
Anderson Darling test is not correct

### ISSUE THREAD

**Issue by nignatiadis** [JuliaStats/HypothesisTests.jl#94]
Hi,

I just noticed that in the Anderson Darling test the observations are standardized to mean 0 and variance 1. However, this is nonsensical for anything except a Normal distribution (the tests of course work since they are based on Normal(0,1)). For example, a standard use case is to compare against a Uniform and this fails:

```
# x from Kolmogorov-Smirnov test in this package
x = [0.3500, 0.1966, 0.2511, 0.6160, 0.4733,
     0.3517, 0.8308, 0.5853, 0.5497, 0.9172,
     0.2858, 0.7572, 0.7537, 0.3804, 0.5678,
     0.0759, 0.0540, 0.5308, 0.7792, 0.9340,
     0.1299, 0.5688, 0.4694, 0.0119, 0.3371
]
t = OneSampleADTest(x, Uniform())
```

Also note that the Anderson-Darling statistic under the null (at least for a continuous distribution) is "distribution-free" (just as Kolmogorov-Smirnov is). However, even in the Normal case, the implementation here also estimates the mean and variance parameters, therefore the null distribution of the Anderson-Darling statistic will no longer be the "distribution-free" one (instead it will be biased towards lower values).  

I have not opened a pull request since I am not sure what the approximations in `pvalue(x::OneSampleADTest)` are actually computing (i.e. if they are actually calibrated to goodness of fit test of a Normal with unknown or known parameters).

**Comment by ararslan** [comment]
I want to say this is a known issue but I'm not entirely certain. @johnmyleswhite may know better than I would.

**Comment by nignatiadis** [comment]
Ah I am sorry for opening this issue; missed https://github.com/JuliaStats/HypothesisTests.jl/issues/56.

**Comment by ararslan** [comment]
No problem. I knew this was familiar, I just didn't remember that there was already an issue for it. I'll close this then in favor of the other. Thanks for the report!
