### ISSUE TITLE
Fisher should buffer results

### ISSUE THREAD

**Issue by nico202** [JuliaStats/HypothesisTests.jl#96]
Hi, if I do f = FisherExactTest(here,some,big,values) it takes quite a bit time to run.
Now, if you want to see the results again, write "f" and you have to wait that time again, it's... boring

Thanks, Nicolò

**Comment by ararslan** [comment]
Fisher's exact test is often slow for large values simply by nature of the test. The issue with printing the results is that the p-values are computed each time `show` is called. I don't think there's currently any built-in mechanism in Julia that permits easily buffering results in the way you suggest. The best I can think to do is
```julia
results = sprint(show, f)
```
Then do `println(results)` to see the results again.

**Comment by simonster** [comment]
The confidence interval probably takes much longer than the p-value. If you don't care about the CI, `f = pvalue(FisherExactTest(here,some,big,values))` and the problem is solved. In any case, I'm not convinced this is something we should change in the package.

**Comment by nico202** [comment]
Yes just asking for the p value worked.
It seems just strange that we are doing a slow computation many times, that's all.
Thanks, Nicolò
