### ISSUE TITLE
The p value of BinomialTest is not equal to other toolkit like R or scipy

### ISSUE THREAD

**Issue by jianixrabbit** [JuliaStats/HypothesisTests.jl#98]
The julia output of the BinomialTest with two sided is

```julia
julia> pvalue(BinomialTest(39,215,0.15))
0.23567888964723258
```
But the same in R is
```R
> binom.test(39,215,0.15)

        Exact binomial test

data:  39 and 215
number of successes = 39, number of trials = 215, p-value = 0.2135
alternative hypothesis: true probability of success is not equal to 0.15
95 percent confidence interval:
 0.1322842 0.2395223
sample estimates:
probability of success 
             0.1813953 
```
And in scipy
```python
scipy.stats.binom_test( 39, 215, 0.15)
0.21352049955117475
```
Look up the source code,the julia's p value implementation is
```julia
pvalue(dist::DiscreteUnivariateDistribution, x::Number; tail=:both) =
    if tail == :both
        min(2 * min(ccdf(dist, x-1), cdf(dist, x)), 1.0)
    elseif tail == :left
        cdf(dist, x)
    elseif tail == :right
        ccdf(dist, x-1)
    else
        throw(ArgumentError("tail=$(tail) is invalid"))
end
```
And R implemented as is
[REMOVED]

It look likes that the R version use a correcting algorithm.Though I don't kown which one is more  robuster，but the output of p value is not equivalent as figure out.

**Comment by nalimilan** [comment]
Please don't copy code from other software here. R is licensed under the GPL, while this package uses the MIT license. Reading the R code before writing a Julia implementation can make this package a derivative work and go against the GPL.

I hope somebody can comment regarding the correction, but you may be able to find references about the two approaches.

**Comment by andreasnoack** [comment]
Two-sided p-values are not well defined when the distribution is asymmetric. See http://www3.imperial.ac.uk/pls/portallive/docs/1/25061696.PDF. We use Fisher's version and R and Scipy use the *minimum likelihood* method. For most tests, it only matters which one you use in borderline cases.

**Comment by andreasnoack** [comment]
Maybe I should add that it is probably okay to add an option for the other version if you'd like to open a PR.
